/// The Flutter pin and the golden image live in more than one file each, and
/// doc 01 says they "must never disagree". That was a rule nobody could enforce
/// by reading: the version appears in `ci.yml`, in `watch-observation.yml`, in
/// the goldens Dockerfile and in doc 01 itself, and three of those four are
/// files a person opens once a year.
///
/// This is the enforcement. It is deliberately text-scanning rather than YAML
/// parsing — `package:yaml` is only in the tree transitively, so importing it
/// would trip `depend_on_referenced_packages` and fail `flutter analyze`, which
/// gates every PR (doc 13 prefers our own fifty lines anyway).
///
/// It lives in `test/repo/` rather than `test/architecture/`: those tests are
/// about the app's internal boundaries, these are about the repo's agreements
/// with itself, and nothing under `.github/`, `tool/` or `packaging/` is
/// covered by any other test in this suite.
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Files that name the Flutter version, and how to find it in each.
///
/// Five, now that there is a release workflow. That is the point: doc 01 says
/// they "must never disagree", and five files kept in step by memory is a rule
/// that is already broken somewhere nobody has looked.
const Map<String, String> _flutterPinSources = <String, String>{
  '.github/workflows/ci.yml': r'FLUTTER_VERSION:\s*"([\d.]+)"',
  '.github/workflows/release.yml': r'FLUTTER_VERSION:\s*"([\d.]+)"',
  '.github/workflows/watch-observation.yml': r'flutter-version:\s*"([\d.]+)"',
  'tool/goldens/Dockerfile': r'ARG\s+FLUTTER_VERSION=([\d.]+)',
  'tool/linux/Dockerfile': r'ARG\s+FLUTTER_VERSION=([\d.]+)',
  'docs/01_TECH_STACK.md': r'\*\*Flutter\s+([\d.]+)\s+stable\*\*',
};

String _read(String relative) {
  final file = File(relative);
  expect(
    file.existsSync(),
    isTrue,
    reason:
        '$relative is missing. If it moved, this test moved with it — the pin '
        'it carries still has to agree with the others.',
  );
  return file.readAsStringSync();
}

String _single(String relative, String pattern) {
  final matches = RegExp(pattern).allMatches(_read(relative)).toList();
  expect(
    matches,
    hasLength(1),
    reason:
        '$relative should state its version exactly once, matching /$pattern/. '
        'Found ${matches.length}. Two of them is how they start to disagree.',
  );
  return matches.single.group(1)!;
}

void main() {
  test('every file that names the Flutter version names the same one', () {
    final found = <String, String>{
      for (final MapEntry<String, String> source in _flutterPinSources.entries)
        source.key: _single(source.key, source.value),
    };

    final distinct = found.values.toSet();
    expect(
      distinct,
      hasLength(1),
      reason:
          'The Flutter pin disagrees across files: $found. doc 01 is the '
          'source of truth; bump every one of these together, never just the '
          'runner.',
    );
  });

  test('the golden job runs on the image its own container is built from', () {
    // A golden is a byte comparison, so the image that checks one has to be the
    // image that made it. Generating the first goldens on Windows against an
    // Ubuntu reference already cost four of five images once (doc 12), and
    // `ubuntu-latest` moving from 24.04 to 26.04 would do the same thing to all
    // of them at once — while looking like a flake rather than a version bump.
    final dockerfile = _read('tool/goldens/Dockerfile');
    final from = RegExp(
      r'^FROM\s+ubuntu:([\d.]+)',
      multiLine: true,
    ).firstMatch(dockerfile);
    expect(
      from,
      isNotNull,
      reason: 'tool/goldens/Dockerfile no longer starts FROM an ubuntu tag.',
    );

    final ci = _read('.github/workflows/ci.yml');
    final goldenJob = RegExp(
      r'^  golden:\n(?<body>(?:.*\n)*?)^  \w',
      multiLine: true,
    ).firstMatch(ci);
    expect(
      goldenJob,
      isNotNull,
      reason: 'ci.yml no longer has a top-level `golden:` job.',
    );

    final runsOn = RegExp(r'runs-on:\s*ubuntu-([\d.]+)')
        .firstMatch(goldenJob!.namedGroup('body')!);
    expect(
      runsOn,
      isNotNull,
      reason:
          'The golden job must pin an explicit ubuntu image. `ubuntu-latest` '
          'is a moving target and goldens are the thing that notices it '
          'moving.',
    );

    expect(
      runsOn!.group(1),
      from!.group(1),
      reason:
          'The golden job runs on ubuntu-${runsOn.group(1)} while '
          'tool/goldens/Dockerfile builds on ubuntu:${from.group(1)}. The '
          'references were generated by the second and are compared by the '
          'first; they have to be the same image.',
    );
  });
}
